#!/usr/bin/env php
<?php

use druidfi\GdprDump\Command\DumpCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/_bootstrap.php';

$app = new Application('mysqldump', '1.0.0');
$command = new DumpCommand();
$app->add($command);
$app->setDefaultCommand($command->getName(), true);
$app->run();
